# Generated by Django 5.2.9 on 2026-07-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField()),
                ("reasoning", models.TextField(blank=True)),
                ("breakdown", models.JSONField(blank=True, default=list)),
                (
                    "model_name",
                    models.CharField(default="rule-based-v1", max_length=40),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="jobs.jobposting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
