# Generated by Django 5.2.9 on 2026-07-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobscore",
            name="embedding",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobscore",
            name="similarity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
