# Generated by Django 5.2.9 on 2026-07-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_jobscore_embedding_jobscore_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobscore',
            name='breakdown_ru',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
