# Generated by Django 5.2.9 on 2026-07-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("upwork_client_id", models.CharField(max_length=64, unique=True)),
                ("verified_payment", models.BooleanField(default=False)),
                ("hire_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "total_spent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=80)),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("total_jobs", models.PositiveIntegerField(blank=True, null=True)),
                ("total_hires", models.PositiveIntegerField(blank=True, null=True)),
                ("member_since", models.DateField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("categories", models.JSONField(blank=True, default=list)),
                (
                    "min_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("require_verified_payment", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("poll_interval_min", models.PositiveSmallIntegerField(default=15)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_id", models.CharField(max_length=96, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                (
                    "budget_type",
                    models.CharField(
                        choices=[("hourly", "Почасовая"), ("fixed", "Фикс")],
                        max_length=8,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("proposals_bucket", models.CharField(blank=True, max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("scored", "Оценена"),
                            ("drafted", "Черновик готов"),
                            ("reviewed", "Одобрена"),
                            ("applied", "Отправлена"),
                            ("skipped", "Пропущена"),
                            ("expired", "Устарела"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="jobs.clientprofile",
                    ),
                ),
                (
                    "matched_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="jobs.savedfilter",
                    ),
                ),
            ],
            options={
                "ordering": ("-posted_at",),
                "indexes": [
                    models.Index(
                        fields=["status"], name="jobs_jobpos_status_99cc43_idx"
                    ),
                    models.Index(
                        fields=["-posted_at"], name="jobs_jobpos_posted__b98875_idx"
                    ),
                ],
            },
        ),
    ]
