# Generated by Django 5.2.9 on 2026-07-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="hired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="interviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
