# Generated by Django 5.2.9 on 2026-07-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobposting_hired_at_jobposting_interviewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="review_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
