# Generated by Django 5.2.9 on 2026-07-08 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_review_notified_at'),
        ('tracks', '0002_seed_default_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfilter',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filters', to='tracks.track'),
        ),
    ]
