# Generated by Django 5.2.9 on 2026-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_savedfilter_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='title_ru',
            field=models.TextField(blank=True),
        ),
    ]
