# Generated by Django 5.2.9 on 2026-07-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobposting_description_ru_jobposting_title_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=96, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='jobs_seenjo_created_62a894_idx')],
            },
        ),
    ]
