# Generated by Django 5.2.9 on 2026-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_backfill_seenjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfilter',
            name='vibeworker_filter_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
