# Generated by Django 5.2.9 on 2026-09-27 05:17

from django.db import migrations, models
from django.db.models import F


def backfill(apps, schema_editor):
    # Best guess for jobs sent before applied_at existed: their last update.
    JobPosting = apps.get_model("jobs", "JobPosting")
    JobPosting.objects.filter(status="applied", applied_at__isnull=True).update(applied_at=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_backfill_seenjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
