# Generated by Django 5.2.9 on 2026-09-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='connects_spent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
