# Generated by Django 5.2.9 on 2026-07-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used for jobs whose saved search has no track.')),
                ('scorer_role', models.CharField(default='freelance developer', help_text='Who you are, one line — steers the scoring prompt.', max_length=200)),
                ('job_analysis_prompt', models.TextField(blank=True, help_text="How to judge a job's fit (fed to the LLM scorer).")),
                ('cover_letter_instructions', models.TextField(blank=True, help_text='How to write the cover letter.')),
                ('screening_instructions', models.TextField(blank=True, help_text='How to answer client screening questions.')),
                ('signoff', models.CharField(default='Best,\nFreelancer', max_length=120)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('min_hourly_rate', models.PositiveSmallIntegerField(default=0)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('red_flag_phrases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('-is_default', 'name'),
            },
        ),
    ]
