# Generated by Django 5.2.9 on 2026-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_seed_default_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='mode',
            field=models.CharField(choices=[('off', 'Выключен: не собирает вакансии'), ('manual', 'Вручную: пинг в Telegram, письмо пишу сам'), ('autopilot', 'Автопилот: готовое письмо сразу в Telegram')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='track',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Куда слать карточки трека (например, чат ассистента). Пусто: TELEGRAM_CHAT_ID', max_length=32),
        ),
    ]
