# Generated by Django 5.2.9 on 2026-09-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='newcomer_mode',
            field=models.BooleanField(default=False, help_text='Пока нет отзывов: предпочитать вакансии, которые реально выиграть. Снять после 3 отзывов', verbose_name='Режим новичка'),
        ),
    ]
