# Generated by Django 5.2.9 on 2026-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_newcomer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='testimonials',
            field=models.TextField(blank=True, help_text='Настоящие отзывы клиентов, по одному на строку: текст | Имя, должность, компания. Письмо цитирует один подходящий. Пусто: письма отзывы не упоминают', verbose_name='Отзывы'),
        ),
    ]
