# Generated by Django 5.2.9 on 2026-07-03 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetterDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveSmallIntegerField(default=0)),
                ("body", models.TextField(blank=True)),
                ("segments", models.JSONField(blank=True, default=list)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "model_name",
                    models.CharField(default="mock-template-v1", max_length=40),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_drafts",
                        to="jobs.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ("-version",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "version"), name="uniq_job_version"
                    )
                ],
            },
        ),
    ]
