# Generated by Django 5.2.9 on 2026-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletterdraft',
            name='body_ru',
            field=models.TextField(blank=True),
        ),
    ]
