# Generated by Django 5.2.9 on 2026-09-27 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('kind', models.CharField(choices=[('connects', 'Покупка коннектов'), ('subscription', 'Подписка'), ('other', 'Другой расход'), ('income', 'Доход')], default='connects', max_length=12)),
                ('usd', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('connects', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
    ]
