# Generated by Django 5.2.9 on 2026-09-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyentry',
            name='kind',
            field=models.CharField(choices=[('connects', 'Покупка коннектов'), ('spent', 'Коннекты на отклик'), ('subscription', 'Подписка'), ('other', 'Другой расход'), ('income', 'Доход')], default='connects', max_length=12),
        ),
    ]
